baseURL = 'https://danielramirez0.com/'
languageCode = 'en-us'
title = "Daniel's Portfolio"
googleAnalytics = "UA-286825744"
# theme = "basic"
theme = "basic"
disqusShortname = "danielramirez0"
Paginate = 10

[params]
    author = "Daniel Ramirez"
    description = "My Portfolio site"
    gh_url= "https://api.github.com/users"
    gh_user= "danielramirez0"

pygmentsUseClasses = true

[permalinks]
    posts = "posts/:year/:month/:slug/"
    year = "/posts/:slug"
    month = "/posts/:slug"

[taxonomies]
    year = "year"
    month = "month"
    tag = "tags"
    category = "categories"

[deployment]
  [[deployment.targets]]
  name = "prod"
  URL = "s3://bph-pp-hugoprod1?region=us-east-1"
  [[deployment.matchers]]
  pattern = "^.+\\.(html|xml|js|css)$"
  gzip = true