baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Daniel Ramirez Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
disqusShortname: danielramirez0
googleAnalytics: "UA-286825744"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    # Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Daniel Ramirez Profile"
  description: A personal portfolio website built with Hugo. Leverages Hugo themes and is hosted on Netlify.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/af-fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  cloudinary_cloud_name: "dxwhmjf96"

  # Whether the fade animations on the home page will be enabled
  animate: true

  # Enable Sticky Nav
  stickyNav: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Daniel Ramirez" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello there, my name is"
    title: "Daniel."
    subtitle: "Air Force Veteran. Father. Full-Stack Software Engineer."
    content: "A passionate engineer and builder. Being an involved parent, I understand the value of time. Let me do the heavy lifting so you can focus on more important things."
    image: https://res.cloudinary.com/dxwhmjf96/image/upload/f_auto,q_auto/v1/Portfolio/HeroImage
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/docs/resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/danielramirez0
        - icon: fab fa-twitter
          url: https://twitter.com/danramirez0
        - icon: fab fa-linkedin-in
          url: https://linkedin.com/in/daniel-ramirez-243b8ba8
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: https://res.cloudinary.com/dxwhmjf96/image/upload/c_thumb,g_auto,h_0.75,w_1.00/Portfolio/AboutMeImage.jpg
    content: |-
      I am a software engineer with a passion for web development, platform engineering, and devops automation. My background is quite diverse with education and certifications in full-stack web development, cyber security, information system architecture, network design, and automation. I leverage my unique experience to design secure, optimal, and automated software delivery solutions, build dynamic web applications, and more. I have a strong interest in platforms and leveraging the power of the cloud-native design. I am currently working as a full-stack software engineer at [VMware Tanzu](https://tanzu.vmware.com/tanzu). 

      I am currently building an image analysis application which uses machine learning to organize images automatically. You can check out the progress [here](#WIP)

    skills:
      enable: true
      title: "I have experience with the following technologies"
      items:
        - "HTML/CSS"
        - "JavaScript"
        - "MongoDB/DynamoDB"
        - "Express"
        - "React"
        - "Node"
        - "Python"
        - "Django"
        - "Hugo"
        - "AWS Services"
        - "Docker"
        - "Kubernetes"
        - "SQL"
        - "C#"
        - ".NET"
        - "PowerShell"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Full-Stack Software Engineer"
        company: "VMware Tanzu"
        companyUrl: "https://tanzu.vmware.com/tanzu"
        date: "Aug 2021 - present"
        featuredLink:
          enable: true
          name: "VMware Tanzu"
          url: "https://github.com/vmware-tanzu"
        content: "I am currently working as a full-stack software engineer at [VMware Tanzu](https://tanzu.vmware.com/tanzu) in Palo Alto, CA. I am a primary maintainer of the [Tanzu Developer Center](https://tanzu.vmware.com/devloper). As an engineer in the customer experience and success organization, I provide support on internal learning management systems which power [Kube Academy](https://kube.academy), [Tanzu Academy](https://tanzu.academy), and [Spring Academy](https://spring.academy)."

      - job: "Platform Engineer Staff"
        company: "Lockheed Martin"
        companyUrl: "https://lockheedmartin.com"
        date: "Jul 2019 - Aug 2021"
        featuredLink:
          enable: false
          # url: "https://example.com"
        info:
          enable: true
          content: I worked as a primary engineer on the team responsible for platform development.
        content: |
          I was the principle network engineering expert for our platform team. I also led projects on automation of system configuration, security hardening, and delivery at Lockheed Martin Skunkworks in Palmdale, CA. I held a Top Secret clearance with Secure Compartmented Information (SCI) access and worked on highly secure and isolated systems. I wrote automation algorithms for system deployment and management. 

      - job: "Infrastructure Team Lead"
        company: "Booz Allen Hamilton"
        companyUrl: "https://boozallen.com"
        date: "Feb 2015 - Jul 2019"
        info:
          enable: true
          content: I ran a small team of administrators responsible for the software developer platform.
        featuredLink:
          enable: false
          # url: "https://example.com"
        content: |
          As the manager of the infrastructure team, I was responsible for design of system architecture, including servers, networks, and third party integrations of highly secure and classified information systems. Additionally, I planned and orchestrated team tasking and hardware/software purchase budgets. I led technical training of new personnel and customers. I designed automation algorithms for system administration tasking. I wrote technical documentation for various system aspects. I began as a security administrator and utilized a variety of training and education sources to rapidly develop my skills and eventually lead the team.

      - job: "Airborne Cryptology Language Analyst"
        company: "United States Air Force"
        companyUrl: "https://airforce.com"
        date: "Dec 2010 - Mar 2015"
        info:
          enable: true
          content: "I served as a dedicated United States Air Force Airman with and gained a wealth of experience and skills"
        content: |-
            As a US Air Force veteran, I bring a unique blend of technical prowess, leadership, adaptability, and dedication to my civilian pursuits. My military experience has equipped me with invaluable skills that regularly apply to new challenges and opportunities.

            - Extensive training and education in technical specialties and leadership.
            - Specialized technical expertise in language analysis, cryptography, avionics, and more.
            - Proven leadership abilities with a strong sense of discipline and decision-making.
            - Adept at working collaboratively within diverse teams to achieve goals.
            - Highly skilled problem solver, able to analyze and resolve complex situations.
            - Exceptional adaptability and resilience cultivated through diverse deployments.
            - Possession of valuable security clearances, demonstrating trustworthiness.
            - A global perspective acquired through international assignments.
            - A steadfast commitment to duty and a strong work ethic.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science in Cyber Security"
        school:
          name: "Maryville University, St. Louis"
          url: "https://www.maryville.edu/"
        date: "2017 - 2018"
        GPA: "4.0"
        # content: |-
          # lorem
      - title: "Bachelor of General Studies with a concentration in Criminal Justice"
        school:
          name: "University of Nebraska, Omaha"
          url: "https://www.unomaha.edu/"
        date: "2013 - 2015"
        GPA: "3.9"
      - title: "Associates of Persian Studies"
        school:
          name: "Defense Language Institute, Foreign Language Center"
          url: "https://www.dliflc.edu/"
        date: "2011 - 2012"
        GPA: "4.0"
        # content: |-
          # lorem
        # featuredLink:
          # enable: true
          # name: "My academic record"
          # url: "https://example.com"
  # Achievements
  achievements:
    enable: true
    title: "Certifications and Training"
    items:
      - title: Certified Information Systems Security Professional
        content: Security Industry Professional Certification
        url: https://my.isc2.org/
        image: /images/cissp-cert.png
      - title: Dev Code Camp Completion Certificate
        content: Web developer boot camp focusing on MERN stack.
        url: https://devcodecamp.com/
        image: /images/dcc-web-dev-cert.png
      - title: Dev Code Camp Completion Certificate
        content: Software developer boot camp using C#, .NET, Python, Django, and MERN stack.
        url: https://devcodecamp.com/
        image: /images/dcc-software-dev-cert.png

  # projects
  projects:
    enable: false #TODO
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: I love meeting and connecting with people. My inbox is always open. Whether you have a question or just want to say hi, please don't hesitate to reach out!
    email: mail@danielramirez0.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/danielramirez0
      linkedin: https://linkedin.com/in/daniel-ramirez-243b8ba8
      twitter: https://twitter.com/danielramirez0
      instagram: https://instagram.com/0danielramirez

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
