baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Daniel's Portfolio"
googleAnalytics = "UA-286825744"
# theme = "basic"
theme = "basic"

[params]
    author = "Daniel Ramirez"
    description = "My Portfolio site"
    gh_url= "https://api.github.com/users"
    gh_user= "danielramirez0"

pygmentsUseClasses = true